spring:
  application:
    name: users-service

server:
  port: ${PORT:8090}

eureka:
  client:
    serviceUrl:
      defaultZone: ${DISCOVERY_URL:http://localhost:8761/eureka/}
    instance:
      leaseRenewalIntervalInSeconds: 1
      leaseExpirationDurationInSeconds: 2

ribbon:
  eureka:
    enabled: true

data:
  mongodb:
  database: users
  host: ${DB_HOST:localhost}
  port: ${DB_PORT:27017}