spring:
  application:
    name: users-service
  datasource:
    platform: postgres
    username: postgres
    password: senha
    url: jdbc:postgresql://localhost:5431/Users
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    database: POSTGRESQL
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
  database:
    driverClassName: org.postgresql.Driver


server:
  port: ${PORT:8090}

eureka:
  client:
    serviceUrl:
      defaultZone: ${DISCOVERY_URL:http://localhost:8761/eureka/}
    instance:
      leaseRenewalIntervalInSeconds: 1
      leaseExpirationDurationInSeconds: 2

ribbon:
  eureka:
    enabled: true
