server:
  port: 8080

ribbon:
  eureka:
    enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: ${DISCOVERY_URL:http://localhost:8761/eureka/}
    registerWithEureka: false

endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false

zuul:
  prefix: /api
  routes:
    products:
      path: /products-service/**
      serviceId: products-service
    auth:
      path: /auth/**
      serviceId: ms-auth
    sales:
      path: /sales-service/**
      serviceId: sales-service


